version: '3'

services:
  mysql:
    build: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=sample
    ports:
      - 3306:3306
volumes:
  mysql-data:
    driver: local
